
# version: '3.9'
# services:
#   web:
#     build: .
#     command: python3 manage.py runserver 127.0.0.1:8000
#     volumes:
#       - .:/code
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#   db:
#     image: postgres:14
#     environment:
#       - "POSTGRES_HOST_AUTH_METHOD=trust"
#     volumes:
#       - .db:/var/lib/postgresql/data/


version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"