# Generated by Django 4.2.3 on 2023-08-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='product_liked',
            new_name='product',
        ),
    ]
