# Generated by Django 4.2.3 on 2023-08-03 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_alter_comment_rate_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name :')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name :')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('datetime_order', models.DateField(auto_now_add=True)),
                ('datetime_order_modified', models.DateField(auto_now=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('order_note', models.TextField(blank=True, verbose_name='Do You Have Any Note For This Order?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
