# Generated by Django 4.2.3 on 2023-07-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('datetime_add', models.DateTimeField(auto_now_add=True)),
                ('datetime_edit', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='product_img/')),
                ('seller', models.CharField(max_length=100)),
            ],
        ),
    ]
