# Generated by Django 4.2.3 on 2023-08-02 13:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_comment_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.CharField(blank=True, choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'normal'), ('4', 'good'), ('5', 'very good')], max_length=10, verbose_name='rate this product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='write your comment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='des',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
