# Generated by Django 4.2.3 on 2023-10-27 19:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_comment_rate_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
    ]
